services:
  redis:
    image: redis:7.4-bookworm
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16-bookworm
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready --quiet -U $POSTGRES_USER -d postgres" ]
      interval: 1s
      retries: 10
      start_period: 5s
  crm:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
      interval: 10s
      retries: 10
      start_period: 1s
    env_file:
      - .env
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
    command: ["go", "run", "cmd/rybakcrm/main.go"]