env: "local"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
db:
  postgres:
    host: "localhost"
    port: "5432"
    username: "vovka"
    ssl_mode: "disable"
    db_name: "rybakcrm"
  redis:
    host: "localhost"
    port: "6379"
migrations:
  path: "schema"
  table: "schema_migrations_test"
  schema_name: "app"
jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 720h